### ISSUE TITLE
Please update libpng to 1.6.34

### ISSUE THREAD

**Issue by djevtic87** [ashtons/libtiff-ios#17]
Please update the libpng to 1.6.34.

> --- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-PNG_NAME        := libpng-1.6.31
+PNG_NAME        := libpng-1.6.34
 JPEG_SRC_NAME   := jpegsrc.v9a# filename at the server
 JPEG_DIR_NAME   := jpeg-9a# folder name after the JPEG_SRC_NAME archive has been unpacked
 TIFF_NAME       := tiff-4.0.8

**Comment by ashtons** [comment]
It's already been updated to 1.6.34 about 10 days ago
